---

- name: Install MySQL package
  yum: name={{ item }} state=installed
    - mysql-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: status.rc !=0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dst=/etc/my.cnf
  notify:
    - restart mysql

- name: Start the mysql service
  service: name=mysqld state=started enabled=yes

- name: insert iptables rules for the mysql software
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}""
              insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport {{mysql_port }} " -j ACCEPT"
  notify: restart iptables

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present

  